CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL,
  "email" varchar(25) UNIQUE NOT NULL,
  "password" varchar(25) NOT NULL,
  "age" int NOT NULL,
  "rol" int NOT NULL
);

CREATE TABLE "course_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(25) NOT NULL,
  "url" varchar(25) NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category" varchar(25) NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rol" varchar(25) NOT NULL
);

CREATE TABLE "level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(25) NOT NULL
);

CREATE TABLE "title" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(25) NOT NULL
);

CREATE TABLE "description" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" varchar(50) NOT NULL
);

CREATE TABLE "teacher" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "teacher" varchar(25) NOT NULL
);

CREATE TABLE "course_general" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_description" int NOT NULL,
  "course_level" int NOT NULL,
  "course_teacher" int NOT NULL,
  "course_user" int NOT NULL,
  "course_category" int NOT NULL,
  "course_videos" int NOT NULL,
  "course_name" int NOT NULL,
  "course_age" int NOT NULL,
  "course_title" int NOT NULL
);

ALTER TABLE "course_general" ADD FOREIGN KEY ("course_level") REFERENCES "level" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("course_teacher") REFERENCES "teacher" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("course_title") REFERENCES "title" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("course_videos") REFERENCES "course_videos" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("course_category") REFERENCES "categories" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("course_description") REFERENCES "description" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("course_user") REFERENCES "users" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("rol") REFERENCES "roles" ("id");

curses_user=# \dt;
            Listado de relaciones
 Esquema |     Nombre     | Tipo  |  Due±o
---------+----------------+-------+----------
 public  | categories     | tabla | postgres
 public  | course_general | tabla | postgres
 public  | course_videos  | tabla | postgres
 public  | description    | tabla | postgres
 public  | level          | tabla | postgres
 public  | roles          | tabla | postgres
 public  | teacher        | tabla | postgres
 public  | title          | tabla | postgres
 public  | users          | tabla | postgres
(9 filas)


curses_user=# INSERT INTO roles (rol) VALUES ('Student'), ('Teacher'),
curses_user-#  ('Admin');
INSERT 0 3
curses_user=# SELECT * FROM roles;
 id |   rol
----+---------
  1 | Student
  2 | Teacher
  3 | Admin
(3 filas)

curses_user=# INSERT INTO users (name, email,password, age, rol) VALUES
curses_user-# ('damian', 'damian@gmail.com', 'dam122', 44, 1),
curses_user-# ('gerson', 'gerson@gmail.com', 'gerso32', 32, 1),
curses_user-# ('carlos', 'carlos@gmail.com', 'car655', 25, 1);
INSERT 0 3
curses_user=# SELECT * FROM users;
 id |  name  |      email       | password | age | rol
----+--------+------------------+----------+-----+-----
  1 | damian | damian@gmail.com | dam122   |  44 |   1
  2 | gerson | gerson@gmail.com | gerso32  |  32 |   1
  3 | carlos | carlos@gmail.com | car655   |  25 |   1
(3 filas)

curses_user=# INSERT INTO categories (category) VALUES ('Front End'), ('Back End'), ('Robotica'), ('IA');
INSERT 0 4
curses_user=# SELECT * FROM categories;
 id | category
----+-----------
  1 | Front End
  2 | Back End
  3 | Robotica
  4 | IA
(4 filas)

curses_user=# INSERT INTO description (description) VALUES ('Desarrolla tu web de manera profesional'), ('Contruye bases
de datos'), ('Conoce las bases de robotica');
INSERT 0 3
curses_user=# SELECT * FROM description;
 id |               description
----+-----------------------------------------
  1 | Desarrolla tu web de manera profesional
  2 | Contruye basesde datos
  3 | Conoce las bases de robotica
(3 filas)


curses_user=# INSERT INTO teacher (teacher) VALUES ('Brenda'), ('Ian'), ('Marcos');
INSERT 0 3
curses_user=# SELECT * FROM teacher;
 id | teacher
----+---------
  1 | Brenda
  2 | Ian
  3 | Marcos
(3 filas)

curses_user=# INSERT INTO title (title) VALUES ('React js'), ('Node Js'), ('Python');
INSERT 0 3
curses_user=# SELECT * FROM title;
 id |  title
----+----------
  1 | React js
  2 | Node Js
  3 | Python
(3 filas)

curses_user=# INSERT INTO course_videos (title, url) VALUES
curses_user-# ('React js', 'https://www.youtube.com/'),
curses_user-# ('Node js', 'https://www.vimeo.com/'),
curses_user-# ('Robotica', 'https://www.amazon.com/');
INSERT 0 3
curses_user=# SELECT * FROM course_videos;
 id |  title   |           url
----+----------+--------------------------
  1 | React js | https://www.youtube.com/
  2 | Node js  | https://www.vimeo.com/
  3 | Robotica | https://www.amazon.com/
(3 filas)

curses_user=# INSERT INTO level (level) VALUES ('Principiante'), ('medio'), ('Avanzado');
INSERT 0 3
curses_user=# SELECT * FROM level;
 id |    level
----+--------------
  1 | Principiante
  2 | medio
  3 | Avanzado
(3 filas)

curses_user=# INSERT INTO course_general (course_description, course_level, course_teacher, course_user, course_category, course_videos, course_title) VALUES
curses_user-# (1, 1, 1, 1, 1, 1, 1),
curses_user-# (2, 2, 2, 2, 2, 2, 2),
curses_user-# (3, 3, 3, 3, 3, 3, 3);
INSERT 0 3
curses_user=# SELECT * FROM course_general;
 id | course_description | course_level | course_teacher | course_user | course_category | course_videos | course_title ----+--------------------+--------------+----------------+-------------+-----------------+---------------+--------------  1 |                  1 |            1 |              1 |           1 |               1 |             1 |            1
  2 |                  2 |            2 |              2 |           2 |               2 |             2 |            2
  3 |                  3 |            3 |              3 |           3 |               3 |             3 |            3
(3 filas)

curses_user=# SELECT * FROM users JOIN ROLES ON users.rol=roles.id;
 id |  name  |      email       | password | age | rol | id |   rol
----+--------+------------------+----------+-----+-----+----+---------
  1 | damian | damian@gmail.com | dam122   |  44 |   1 |  1 | Student
  2 | gerson | gerson@gmail.com | gerso32  |  32 |   1 |  1 | Student
  3 | carlos | carlos@gmail.com | car655   |  25 |   1 |  1 | Student
(3 filas)


curses_user=# SELECT users.id, users.name, users.email, users.password, users.age, roles.rol From users JOIN roles ON users.rol=roles.id;
 id |  name  |      email       | password | age |   rol
----+--------+------------------+----------+-----+---------
  1 | damian | damian@gmail.com | dam122   |  44 | Student
  2 | gerson | gerson@gmail.com | gerso32  |  32 | Student
  3 | carlos | carlos@gmail.com | car655   |  25 | Student
(3 filas)

curses_user=# SELECT * FROM course_general JOIN description ON course_description=description.id JOIN level ON level.id=course_level JOIN teacher ON teacher.id=course_teacher JOIN users ON course_user=users.id JOIN categories ON course_category=categories.id JOIN course_videos ON course_videos.id=course_videos JOIN title ON title.id=course_title;
 id | course_description | course_level | course_teacher | course_user | course_category | course_videos | course_title | id |               description               | id |    level     | id | teacher | id |  name  |      email       | password | age | rol | id | category  | id |  title   |           url            | id |  title
----+--------------------+--------------+----------------+-------------+-----------------+---------------+--------------+----+-----------------------------------------+----+--------------+----+---------+----+--------+------------------+----------+-----+-----+----+-----------+----+----------+--------------------------+----+----------
  1 |                  1 |            1 |              1 |           1 |               1 |             1 |            1 |  1 | Desarrolla tu web de manera profesional |  1 | Principiante |  1 | Brenda  |  1 | damian | damian@gmail.com | dam122   |  44 |   1 |  1 | Front End |  1 | React js | https://www.youtube.com/ |  1 | React js
  2 |                  2 |            2 |              2 |           2 |               2 |             2 |            2 |  2 | Contruye basesde datos                  |  2 | medio        |  2 | Ian     |  2 | gerson | gerson@gmail.com | gerso32  |  32 |   1 |  2 | Back End  |  2 | Node js  | https://www.vimeo.com/   |  2 | Node Js
  3 |                  3 |            3 |              3 |           3 |               3 |             3 |            3 |  3 | Conoce las bases de robotica            |  3 | Avanzado     |  3 | Marcos  |  3 | carlos | carlos@gmail.com | car655   |  25 |   1 |  3 | Robotica  |  3 | Robotica | https://www.amazon.com/  |  3 | Python
(3 filas)




